import { Platform, StyleSheet } from "react-native";
export const palette = {
  bg: "#2f5fe0",
  surface: "#ffffff",
  ink: "#1f2937",
  muted: "#6b7280",
  accent: "#2563eb",
  accentAlt: "#fbbf24",
  border: "#d9dee8",
};
export const BOTTOM_NAV_HEIGHT = 56;

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    position: "relative",
  },
  screenArea: {
    flex: 1,
    minHeight: 0,
    paddingTop: 8,
    paddingBottom: 12,
  },
  screenScroll: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  screenContent: {
    paddingBottom: 24,
    backgroundColor: palette.bg,
  },
  screenContentFill: {
    flexGrow: 1,
  },
  mapScreenContent: {
    paddingBottom: 108,
  },
  mapHero: {
    marginBottom: 16,
  },
  mapHeroTitle: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "900",
    marginBottom: 6,
  },
  mapHeroSubtitle: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  mapFilterToolbar: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.08)",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  mapFilterToolbarCopy: {
    flex: 1,
  },
  mapFilterKicker: {
    color: palette.accentAlt,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  mapFilterToolbarText: {
    color: "#ffffff",
    fontSize: 13,
    lineHeight: 18,
  },
  mapFilterTrigger: {
    minHeight: 38,
    borderRadius: 999,
    paddingHorizontal: 12,
    backgroundColor: "rgba(255,255,255,0.12)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  mapFilterTriggerText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  mapList: {
    gap: 12,
  },
  mapProfessionalCard: {
    borderRadius: 18,
    backgroundColor: palette.surface,
    padding: 16,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  mapProfessionalMain: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 12,
  },
  mapPhotoWrapper: {
    position: "relative",
  },
  mapPhotoFrame: {
    width: 74,
    height: 74,
    borderRadius: 18,
    backgroundColor: "#dbe7ff",
    alignItems: "center",
    justifyContent: "center",
  },
  mapPhotoFrameImage: {
    width: 74,
    height: 74,
    borderRadius: 18,
    backgroundColor: "#dbe7ff",
  },
  mapPhotoInitial: {
    color: palette.accent,
    fontSize: 28,
    fontWeight: "900",
  },
  mapTopRatedBadge: {
    position: "absolute",
    right: -6,
    top: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#1f2937",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  mapPhotoStatusBadge: {
    position: "absolute",
    left: "50%",
    bottom: -8,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    transform: [{ translateX: -36 }],
  },
  mapPhotoStatusBadgeOn: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
  },
  mapPhotoStatusBadgeOff: {
    backgroundColor: "#ffffff",
    borderColor: "#e5e7eb",
  },
  mapPhotoStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  mapPhotoStatusText: {
    fontSize: 10,
    fontWeight: "800",
  },
  mapPhotoStatusTextOn: {
    color: "#065f46",
  },
  mapPhotoStatusTextOff: {
    color: "#475569",
  },
  mapProfessionalContent: {
    flex: 1,
  },
  mapProfessionalBottom: {
    width: "100%",
  },
  mapProfessionalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  mapProfessionalNameBlock: {
    flex: 1,
  },
  mapProfessionalName: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 6,
  },
  mapAvailabilityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  mapAvailabilityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  mapAvailabilityDotOn: {
    backgroundColor: "#10b981",
  },
  mapAvailabilityDotOff: {
    backgroundColor: "#94a3b8",
  },
  mapAvailabilityText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  mapRatingBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#1f2937",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  mapRatingBadgeText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
  mapMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 12,
  },
  mapDistanceBadge: {
    flex: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#eef4ff",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    justifyContent: "center",
    minHeight: 34,
  },
  mapDistanceBadgeText: {
    color: palette.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  mapExperienceBadge: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 34,
  },
  mapExperienceBadgeText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: "700",
  },
  mapPriceGrid: {
    flexDirection: "row",
    alignItems: "stretch",
    width: "100%",
    borderRadius: 14,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    marginBottom: 12,
    overflow: "hidden",
  },
  mapPriceItem: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  mapPriceLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 4,
  },
  mapPriceValue: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  mapPriceDivider: {
    width: 1,
    backgroundColor: "#dbe7ff",
  },
  mapProfessionalBio: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  mapCardActions: {
    flexDirection: "row",
    width: "100%",
    gap: 10,
    marginTop: 12,
  },
  mapSecondaryAction: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbe7ff",
    backgroundColor: "#f8fbff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  mapSecondaryActionText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  mapPrimaryAction: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  mapPrimaryActionText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  diaristOfferCardMobile: {
    borderRadius: 20,
    backgroundColor: "#fdfefe",
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#d9e8ff",
    shadowColor: "#0f172a",
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  diaristOfferTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  diaristOfferIdentity: {
    flexDirection: "row",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  diaristOfferPhotoFrame: {
    width: 76,
    height: 76,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#dbe7ff",
  },
  diaristOfferPhoto: {
    width: "100%",
    height: "100%",
  },
  diaristOfferPhotoFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#dbe7ff",
  },
  diaristOfferPhotoFallbackText: {
    color: "#2563eb",
    fontSize: 28,
    fontWeight: "900",
  },
  diaristOfferEyebrow: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    marginTop: 6,
    marginBottom: 4,
  },
  diaristOfferClientName: {
    color: "#1f2937",
    fontSize: 19,
    fontWeight: "900",
    marginBottom: 6,
  },
  diaristOfferRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  diaristOfferRatingValue: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "900",
  },
  diaristOfferRatingText: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "700",
  },
  diaristOfferHeaderActions: {
    width: 170,
    alignItems: "stretch",
    gap: 10,
  },
  diaristOfferWarningChip: {
    alignSelf: "stretch",
    borderRadius: 10,
    backgroundColor: "#fff3d8",
    borderWidth: 1,
    borderColor: "#fed7aa",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  diaristOfferWarningChipText: {
    color: "#c2410c",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  diaristOfferCTAGroup: {
    gap: 10,
  },
  diaristOfferWarningChipInline: {
    marginBottom: 12,
  },
  diaristOfferCounterButton: {
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: "#fbbf24",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#f59e0b",
    shadowOpacity: 0.32,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  diaristOfferCounterButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  diaristOfferAcceptButton: {
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: "#16a34a",
    alignItems: "center",
    justifyContent: "center",
  },
  diaristOfferAcceptButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  diaristOfferProfileButton: {
    minHeight: 40,
    borderRadius: 14,
    backgroundColor: "#2563eb",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2563eb",
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  diaristOfferProfileButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  diaristOfferChipRowMobile: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
  },
  diaristOfferInfoChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  diaristOfferInfoChipText: {
    color: "#315b9a",
    fontSize: 12,
    fontWeight: "700",
  },
  diaristOfferMetricsGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  diaristOfferBottomActions: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  diaristOfferBottomAction: {
    flex: 1,
  },
  diaristOfferBottomActionSpacer: {
    flex: 1,
  },
  diaristOfferProfileButtonStandalone: {
    minHeight: 40,
    borderRadius: 14,
    backgroundColor: "#2563eb",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2563eb",
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    marginBottom: 8,
  },
  diaristOfferMetricCard: {
    flex: 1,
    minHeight: 82,
    borderRadius: 16,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "space-between",
  },
  diaristOfferMetricLabel: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  diaristOfferMetricValue: {
    color: "#1f2937",
    fontSize: 17,
    fontWeight: "900",
  },
  diaristOfferExpandedPanel: {
    marginTop: 10,
  },
  diaristOfferObservationsBox: {
    borderRadius: 16,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    padding: 12,
    marginBottom: 12,
  },
  diaristOfferSectionLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  diaristOfferObservationsText: {
    color: "#334155",
    fontSize: 14,
    lineHeight: 20,
  },
  diaristOfferRoomsBox: {
    borderRadius: 16,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    padding: 12,
  },
  diaristOfferRoomsGrid: {
    flexDirection: "column",
    gap: 10,
  },
  diaristOfferRoomCardMobile: {
    width: "100%",
    minHeight: 78,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  diaristOfferRoomIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#dbe7ff",
    alignItems: "center",
    justifyContent: "center",
  },
  diaristOfferRoomName: {
    color: "#1f2937",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 2,
    flexShrink: 1,
    flexWrap: "wrap",
  },
  diaristOfferRoomMeta: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "600",
    flexShrink: 1,
    flexWrap: "wrap",
  },
  diaristOfferRoomBadge: {
    minWidth: 38,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: "#eef2ff",
    alignItems: "center",
    justifyContent: "center",
  },
  diaristOfferRoomBadgeText: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "900",
  },
  diaristOfferFooterToggle: {
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#dbe7ff",
    paddingTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  diaristOfferFooterToggleText: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "700",
  },
  offersScreenContentCentered: {
    justifyContent: "center",
    paddingTop: 16,
    paddingBottom: 132,
  },
  offersCardCentered: {
    minHeight: 120,
    justifyContent: "center",
  },
  offersTabRow: {
    marginBottom: 14,
  },
  subsectionTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 10,
  },
  sectionCard: {
    borderRadius: 16,
    backgroundColor: palette.surface,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    gap: 12,
  },
  sectionTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "800",
  },
  sectionMeta: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  primaryLine: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 6,
  },
  secondaryLine: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  listCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    backgroundColor: "#fbfdff",
  },
  listTitle: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 6,
  },
  offerCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  offerCardHeaderMain: {
    flex: 1,
    minWidth: 0,
  },
  offerAddressRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  offerScheduleBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#dcfce7",
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  offerScheduleBadgeText: {
    color: "#166534",
    fontSize: 12,
    fontWeight: "800",
  },
  offerHeaderDangerButton: {
    minHeight: 34,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#fee2e2",
    borderWidth: 1,
    borderColor: "#fecaca",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  offerHeaderDangerButtonText: {
    color: "#b91c1c",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  inlineMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  metaBadge: {
    alignSelf: "flex-start",
    marginTop: 8,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#eef4ff",
    color: palette.accent,
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
  },
  emptyState: {
    paddingVertical: 10,
  },
  emptyStateTitle: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 6,
  },
  emptyStateCopy: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  loadingHero: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 26,
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  loadingPulseDot: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    marginBottom: 16,
  },
  loadingHeroTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
    textAlign: "center",
  },
  loadingHeroCopy: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
    maxWidth: 280,
  },
  loadingSectionCard: {
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.96)",
    padding: 16,
    marginBottom: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  loadingSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  loadingToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  loadingToolbarCopy: {
    flex: 1,
  },
  loadingTitleBar: {
    width: 154,
    height: 16,
    borderRadius: 999,
    backgroundColor: "#dbe7ff",
  },
  loadingCountDot: {
    width: 26,
    height: 16,
    borderRadius: 999,
    backgroundColor: "#e7eefc",
  },
  loadingFilterButton: {
    width: 72,
    height: 38,
    borderRadius: 999,
    backgroundColor: "#dbe7ff",
  },
  loadingDiaristCard: {
    flexDirection: "row",
    gap: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#dbe7ff",
    backgroundColor: "#f8fbff",
    padding: 14,
    marginBottom: 10,
  },
  loadingAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#dbe7ff",
  },
  loadingCardBody: {
    flex: 1,
    justifyContent: "center",
  },
  loadingLine: {
    height: 12,
    borderRadius: 999,
    backgroundColor: "#dbe7ff",
    marginBottom: 8,
  },
  loadingLineWide: {
    width: "86%",
  },
  loadingLineMedium: {
    width: "68%",
  },
  loadingLineShort: {
    width: "34%",
    marginBottom: 0,
  },
  loadingLineShorter: {
    width: "22%",
  },
  loadingState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 36,
    gap: 10,
  },
  loadingText: {
    color: palette.muted,
    fontSize: 14,
  },
  errorText: {
    color: "#dc2626",
    fontSize: 13,
    lineHeight: 18,
  },
  warningText: {
    color: "#b45309",
    fontSize: 12,
    fontWeight: "700",
    alignSelf: "center",
  },
  primaryActionButton: {
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    paddingHorizontal: 16,
  },
  primaryActionButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  offerActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  primaryInlineButton: {
    minHeight: 40,
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryInlineButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  secondaryActionButton: {
    minHeight: 40,
    borderRadius: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryActionButtonFilled: {
    backgroundColor: "#eff6ff",
  },
  secondaryActionButtonFilledText: {
    color: palette.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  dangerInlineButton: {
    minHeight: 40,
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: "#fee2e2",
    alignItems: "center",
    justifyContent: "center",
  },
  dangerInlineButtonText: {
    color: "#b91c1c",
    fontSize: 13,
    fontWeight: "800",
  },
  negotiationStack: {
    marginTop: 14,
  },
  nestedCard: {
    borderWidth: 1,
    borderColor: "#dbe4ff",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#f8fbff",
    marginTop: 10,
  },
  negotiationSummary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  negotiationSummaryMain: {
    flex: 1,
  },
  negotiationSummarySide: {
    alignItems: "flex-end",
    gap: 6,
  },
  negotiationChevron: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  negotiationExpanded: {
    marginTop: 12,
    gap: 10,
  },
  profilePreviewButton: {
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    backgroundColor: "#eff6ff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  profilePreviewButtonText: {
    color: "#1d4ed8",
    fontSize: 13,
    fontWeight: "800",
  },
  miniTab: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#eef2f7",
  },
  miniTabActive: {
    backgroundColor: palette.accent,
  },
  miniTabText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: "700",
  },
  miniTabTextActive: {
    color: "#ffffff",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.48)",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    padding: 18,
  },
  modalTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
  },
  modalCopy: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 12,
  },
  modalInput: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: palette.ink,
    backgroundColor: "#fbfdff",
    marginBottom: 10,
  },
  modalTextarea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  modalActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 6,
  },
  offerCreateModalCard: {
    maxWidth: 420,
    borderRadius: 22,
    paddingTop: 18,
    paddingHorizontal: 18,
    paddingBottom: 18,
  },
  offerCreateModalTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 10,
  },
  offerCreateModalAddress: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 12,
  },
  offerCreateModalInput: {
    borderRadius: 14,
    marginBottom: 12,
    backgroundColor: "#ffffff",
    borderColor: "#d7e1ef",
  },
  offerCreateModalPrimaryInput: {
    borderWidth: 2,
    borderColor: "#111827",
  },
  offerCreateModalTextarea: {
    minHeight: 94,
    paddingTop: 12,
  },
  offerCreateModalActions: {
    marginTop: 4,
  },
  mapProfileModalCard: {
    width: "100%",
    maxWidth: "100%",
    height: "100%",
    maxHeight: "100%",
    borderRadius: 0,
    paddingTop: 4,
    minHeight: 440,
    overflow: "hidden",
  },
  mapModalClose: {
    alignSelf: "flex-end",
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#eef2f7",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 0,
  },
  mapModalCloseText: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  mapProfileHeader: {
    alignItems: "center",
    paddingBottom: 6,
    marginBottom: 0,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  mapProfileAvatarWrapper: {
    marginTop: -10,
    marginBottom: 2,
  },
  mapProfileAvatar: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: "#dbe7ff",
  },
  mapProfileAvatarFallback: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: "#dbe7ff",
    alignItems: "center",
    justifyContent: "center",
  },
  mapProfileAvatarFallbackText: {
    color: palette.accent,
    fontSize: 22,
    fontWeight: "900",
  },
  mapProfileName: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 2,
  },
  mapHeaderMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "nowrap",
    gap: 8,
    marginTop: 4,
    width: "100%",
  },
  mapRatingPillLarge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    backgroundColor: "#111827",
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  mapRatingPillLargeText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
  mapRatingPillLargeCount: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 11,
    fontWeight: "600",
  },
  mapVerificationPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
  },
  mapVerificationPillVerified: {
    backgroundColor: "rgba(34, 197, 94, 0.1)",
    borderColor: "rgba(134, 239, 172, 0.9)",
  },
  mapVerificationPillUnverified: {
    backgroundColor: "rgba(248, 113, 113, 0.1)",
    borderColor: "rgba(252, 165, 165, 0.9)",
  },
  mapVerificationPillText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  mapVerificationPillTextVerified: {
    color: "#166534",
  },
  mapVerificationPillTextUnverified: {
    color: "#991b1b",
  },
  mapProfileBody: {
    flex: 1,
    minHeight: 0,
    marginTop: 0,
  },
  mapProfileBodyContent: {
    paddingBottom: 16,
  },
  mapProfileSection: {
    marginTop: 16,
  },
  mapProfileSectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  mapProfileSectionTitle: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  mapProfileSectionCopy: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  mapStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  mapStatCard: {
    width: "48%",
    minHeight: 90,
    borderRadius: 14,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    padding: 12,
    justifyContent: "space-between",
  },
  mapStatLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 8,
  },
  mapStatValue: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    marginTop: 4,
  },
  mapDrawerPricing: {
    flexDirection: "row",
    gap: 10,
  },
  mapDrawerPriceCard: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    padding: 14,
  },
  mapDrawerPriceLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
  },
  mapDrawerPriceValue: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  mapSpecialtiesWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  mapSpecialtyCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#dbeafe",
  },
  mapSpecialtyText: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  mapReviewCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbeafe",
    backgroundColor: "#f8fbff",
    padding: 12,
    marginBottom: 10,
  },
  mapReviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  mapReviewStars: {
    color: palette.accentAlt,
    fontSize: 13,
    fontWeight: "900",
  },
  mapReviewDate: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  mapReviewComment: {
    color: palette.ink,
    fontSize: 13,
    lineHeight: 19,
  },
  mapProfileFooter: {
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 6,
    marginTop: 2,
    flexShrink: 0,
  },
  mapReserveButton: {
    minHeight: 34,
    borderRadius: 10,
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  mapReserveButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  mapFooterNote: {
    color: palette.muted,
    fontSize: 11,
    lineHeight: 14,
    marginBottom: 2,
    textAlign: "center",
    alignSelf: "center",
    maxWidth: 280,
  },
  profileModalCard: {
    maxHeight: "86%",
  },
  reviewsModalCard: {
    maxHeight: "86%",
  },
  modalGhostButton: {
    minHeight: 40,
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: "#eef2f7",
    alignItems: "center",
    justifyContent: "center",
  },
  modalGhostButtonText: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "700",
  },
  profileBio: {
    color: palette.ink,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 12,
    marginBottom: 14,
  },
  reviewCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbeafe",
    backgroundColor: "#f8fbff",
    padding: 12,
    marginTop: 10,
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  reviewStars: {
    color: palette.accentAlt,
    fontSize: 14,
    fontWeight: "800",
  },
  reviewDate: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  reviewsScroll: {
    maxHeight: 420,
  },
  bottomNavigation: {
    position: Platform.OS === "web" ? "fixed" : "absolute",
    bottom: 0,
    left: Platform.OS === "web" ? 0 : -14,
    right: Platform.OS === "web" ? 0 : -14,
    width: Platform.OS === "web" ? "100%" : undefined,
    height: BOTTOM_NAV_HEIGHT,
    backgroundColor: palette.bg,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.1)",
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 12,
    display: "flex",
    paddingBottom: 1,
  },
  bottomNavContainer: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-around",
    height: "100%",
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  navItemActive: {
    backgroundColor: "rgba(251, 191, 36, 0.10)",
    borderBottomWidth: 3,
    borderBottomColor: palette.accentAlt,
  },
  navLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 11,
    fontWeight: "600",
  },
  navLabelActive: {
    color: palette.accentAlt,
  },
  navItemDisabled: {
    opacity: 0.5,
  },
  navLabelDisabled: {
    color: "rgba(255,255,255,0.35)",
  },
  orderShell: {
    flex: 1,
    backgroundColor: "#f8fafc",
    paddingTop: 10,
  },
  orderHeader: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  orderCloseButton: {
    alignSelf: "flex-end",
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#eef2f7",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  orderTitle: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 4,
  },
  orderSubtitle: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: "600",
  },
  orderProgressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#dbe7ff",
    overflow: "hidden",
    marginHorizontal: 16,
    marginBottom: 12,
  },
  orderProgressFill: {
    height: "100%",
    backgroundColor: palette.accent,
  },
  orderProgressSteps: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  orderProgressStep: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#dbe7ff",
    alignItems: "center",
    justifyContent: "center",
  },
  orderProgressStepActive: {
    backgroundColor: "#bfdbfe",
  },
  orderProgressStepCurrent: {
    backgroundColor: palette.accent,
  },
  orderProgressStepText: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "800",
  },
  orderProgressStepTextActive: {
    color: "#ffffff",
  },
  orderBody: {
    flex: 1,
  },
  orderBodyContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  orderSection: {
    borderRadius: 20,
    backgroundColor: "#ffffff",
    padding: 16,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  orderSectionTitle: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 6,
  },
  orderSectionCopy: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  orderOptionsColumn: {
    gap: 12,
  },
  orderOptionCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe7ff",
    backgroundColor: "#f8fbff",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  orderOptionCardActive: {
    borderColor: palette.accent,
    backgroundColor: "#eff6ff",
  },
  orderOptionIcon: {
    fontSize: 22,
  },
  orderOptionTextBlock: {
    flex: 1,
  },
  orderOptionTitle: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 4,
  },
  orderOptionCopy: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  orderHint: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
  },
  orderTimePickerCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe7ff",
    backgroundColor: "#f8fbff",
    padding: 12,
    marginBottom: 8,
  },
  orderTimeDisplayRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 10,
  },
  orderTimeInputWrap: {
    width: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  orderTimeInput: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: "900",
    paddingVertical: 6,
    paddingHorizontal: 0,
  },
  orderTimeSeparator: {
    color: palette.ink,
    fontSize: 26,
    fontWeight: "900",
  },
  orderTimeWheelRow: {
    flexDirection: "row",
    gap: 12,
  },
  orderTimeWheelMiddle: {
    width: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 22,
  },
  orderTimeWheelMiddleText: {
    color: palette.ink,
    fontSize: 28,
    fontWeight: "900",
  },
  orderTimeWheelColumn: {
    flex: 1,
  },
  orderTimeWheelLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 6,
    textTransform: "uppercase",
    textAlign: "center",
  },
  orderTimeWheelWindow: {
    height: 120,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbe7ff",
    backgroundColor: "#ffffff",
    overflow: "hidden",
    position: "relative",
  },
  orderTimeWheelContent: {
    paddingVertical: 40,
    position: "relative",
    zIndex: 2,
  },
  orderTimeWheelHighlight: {
    position: "absolute",
    top: 40,
    left: 6,
    right: 6,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    backgroundColor: "#eff6ff",
  },
  orderTimeWheelFadeTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 36,
    backgroundColor: "rgba(255,255,255,0.72)",
    zIndex: 3,
  },
  orderTimeWheelFadeBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 36,
    backgroundColor: "rgba(255,255,255,0.72)",
    zIndex: 3,
  },
  orderTimeWheelItem: {
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  orderTimeWheelItemText: {
    color: "#475569",
    fontSize: 17,
    fontWeight: "700",
    opacity: 0.38,
    transform: [{ scale: 0.9 }],
  },
  orderTimeWheelItemTextActive: {
    color: "#0f172a",
    fontWeight: "900",
    fontSize: 21,
    opacity: 1,
    transform: [{ scale: 1.06 }],
  },
  orderCalendarCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe7ff",
    backgroundColor: "#f8fbff",
    padding: 12,
  },
  orderCalendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  orderCalendarNavButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  orderCalendarNavButtonText: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "900",
  },
  orderCalendarMonthLabel: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  orderCalendarWeekRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  orderCalendarWeekday: {
    width: "14.28%",
    textAlign: "center",
    color: "#64748b",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  orderCalendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  orderCalendarCell: {
    width: "14.28%",
    padding: 2,
  },
  orderCalendarCellEmpty: {
    width: "14.28%",
    padding: 2,
    height: 42,
  },
  orderCalendarCellButton: {
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    backgroundColor: "#ffffff",
  },
  orderCalendarCellText: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "700",
  },
  orderCalendarCellSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  orderCalendarCellSelectedText: {
    color: "#ffffff",
  },
  orderCalendarCellBlocked: {
    backgroundColor: "#fee2e2",
    borderColor: "#fca5a5",
  },
  orderCalendarCellBlockedText: {
    color: "#b91c1c",
  },
  orderCalendarCellPast: {
    backgroundColor: "#e5e7eb",
    borderColor: "#cbd5e1",
  },
  orderCalendarCellPastText: {
    color: "#64748b",
  },
  orderCalendarCellDisabled: {
    opacity: 0.9,
  },
  orderCalendarLegendRow: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  orderCalendarLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  orderCalendarLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#dbe7ff",
  },
  orderCalendarLegendDotAvailable: {
    backgroundColor: "#ffffff",
  },
  orderCalendarLegendDotBlocked: {
    backgroundColor: "#fee2e2",
    borderColor: "#fca5a5",
  },
  orderCalendarLegendDotPast: {
    backgroundColor: "#e5e7eb",
    borderColor: "#cbd5e1",
  },
  orderCalendarLegendText: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
  },
  orderInlineRow: {
    flexDirection: "row",
    gap: 10,
  },
  orderInlineInput: {
    flex: 1,
  },
  orderChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  orderChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#dbe7ff",
    backgroundColor: "#ffffff",
  },
  orderChipActive: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  orderChipText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: "700",
  },
  orderChipTextActive: {
    color: "#ffffff",
  },
  orderDurationRow: {
    marginTop: 14,
    gap: 8,
  },
  orderLabel: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  orderStepper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  orderStepperButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#eef2ff",
    alignItems: "center",
    justifyContent: "center",
  },
  orderStepperValueWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
  },
  orderStepperButtonText: {
    color: palette.accent,
    fontSize: 20,
    fontWeight: "900",
  },
  orderStepperValue: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "800",
  },
  orderPricePreview: {
    borderRadius: 16,
    backgroundColor: "#eef6ff",
    padding: 14,
    marginTop: 16,
  },
  orderPriceLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  orderPriceValue: {
    color: palette.accent,
    fontSize: 24,
    fontWeight: "900",
  },
  orderCounter: {
    color: palette.muted,
    fontSize: 12,
    textAlign: "right",
    marginTop: -2,
    marginBottom: 12,
  },
  orderAddressInfo: {
    borderRadius: 14,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    padding: 12,
  },
  orderReviewCard: {
    borderRadius: 16,
    backgroundColor: "#f8fbff",
    borderWidth: 1,
    borderColor: "#dbe7ff",
    padding: 14,
    gap: 10,
  },
  orderReviewItem: {
    gap: 4,
  },
  orderReviewLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  orderReviewValue: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 21,
  },
  orderReviewDivider: {
    height: 1,
    backgroundColor: "#dbe7ff",
    marginVertical: 4,
  },
  orderReviewValueTotal: {
    color: palette.accent,
    fontSize: 22,
    fontWeight: "900",
  },
  orderActions: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    backgroundColor: "#ffffff",
  },
  orderSecondaryButton: {
    minHeight: 46,
    borderRadius: 14,
    paddingHorizontal: 18,
    backgroundColor: "#eef2f7",
    alignItems: "center",
    justifyContent: "center",
  },
  orderSecondaryButtonText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  orderPrimaryButton: {
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  orderNextButton: {
    flex: 1,
  },
  orderSuccessButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: "#16a34a",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  orderPrimaryButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
});

